"""initial schema

Revision ID: 501fc94092f5
Revises: 
Create Date: 2026-08-19 18:27:03.138965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501fc94092f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('user', 'company', name='owner_type'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('building_family', sa.Enum('sport', 'study', 'work', 'creativity', 'meditation', 'reading', 'custom', name='building_family_key'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'building_family', name='uq_city_building_owner')
    )
    op.create_index(op.f('ix_city_buildings_owner_id'), 'city_buildings', ['owner_id'], unique=False)
    op.create_table('daily_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('goal_minutes', sa.Integer(), nullable=False),
    sa.Column('goal_met', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_progress_user_date')
    )
    op.create_index(op.f('ix_daily_progress_user_id'), 'daily_progress', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('shape', sa.Enum('circle', 'square', 'triangle', 'hex', 'blob', 'diamond', name='shape_kind'), nullable=False),
    sa.Column('building_family', sa.Enum('sport', 'study', 'work', 'creativity', 'meditation', 'reading', 'custom', name='building_family_key'), nullable=False),
    sa.Column('minutes_per_day_target', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('addressee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'blocked', name='friendship_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    op.create_table('paired_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('building_family', sa.Enum('sport', 'study', 'work', 'creativity', 'meditation', 'reading', 'custom', name='building_family_key'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('combined', 'per_participant', name='paired_task_target_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'expired', 'cancelled', name='paired_task_status'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paired_task_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paired_task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('minutes_logged', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paired_task_id'], ['paired_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paired_task_id', 'user_id', name='uq_paired_task_participant')
    )
    op.create_table('time_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('paired_task_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('timer', 'manual', name='time_entry_source'), nullable=False),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['paired_task_id'], ['paired_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_table('paired_task_participants')
    op.drop_table('paired_tasks')
    op.drop_table('friendships')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_daily_progress_user_id'), table_name='daily_progress')
    op.drop_table('daily_progress')
    op.drop_index(op.f('ix_city_buildings_owner_id'), table_name='city_buildings')
    op.drop_table('city_buildings')
    # ### end Alembic commands ###

    # Postgres ENUM types are not dropped automatically when their tables are
    # dropped -- do it explicitly so downgrade() is actually reversible.
    for enum_name in (
        'owner_type',
        'building_family_key',
        'shape_kind',
        'friendship_status',
        'paired_task_target_type',
        'paired_task_status',
        'time_entry_source',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
